### ISSUE TITLE
Plots are not visible - matplotlib backend error

### ISSUE THREAD

**Issue by hjarupBrewDK** [hirschmann/pid-autotune#1]
Hi Hirschmann,
I could find no other way to contact you directly so ... Therefore i Created this issue.

I followed the guide for install 
1. Install git and python3
2. git clone https://github.com/hirschmann/pid-autotune.git
3. pip install matplotlib

Then : python sim.py --atune --volume 50 --power 4
and first python
and then : sim.py --atune --volume 50 --power 4
(getting errors)

Do I need to do it some other way ? or can you  direct me to more help?

**Comment by ghost** [comment]
I got it working (issue with the installation process) ....
so now i can execute:
python3 sim.py --atune --volume 50 --power 4

It opens a blank graph, and display a couple of this error:

 buf, cairo.FORMAT_ARGB32, width, height)
NotImplementedError: Surface.create_for_data: Not Implemented yet.

**Comment by hirschmann** [comment]
Looks like you're trying to use an unsupported backend for matplotlib, but this is just a wild guess because you haven't posted the full error message.

Try a different backend:
http://matplotlib.org/faq/usage_faq.html#what-is-a-backend
https://matplotlib.org/users/customizing.html#customizing-with-matplotlibrc-files

**Comment by ghost** [comment]
I will look more at the backend ... here is the complete output (this time from root terminal)

Br Carsten
--------------  Complete output   ---------------
```
root@raspberrypi:/home/pi/craftbeerpi/pid-autotune# python3 sim.py --pid 'reference' 98 0.66 230 --pid 'Kp too low' 30 0.66 230 --pid 'Ki too low' 98 0.01 230

** (sim.py:8585): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py:18: UserWarning: The Gtk3Agg backend is known to not work on Python 3.x with pycairo. Try installing cairocffi.
  "The Gtk3Agg backend is known to not work on Python 3.x with pycairo. "
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 69, in on_draw_event
    buf, cairo.FORMAT_ARGB32, width, height)
NotImplementedError: Surface.create_for_data: Not Implemented yet.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 69, in on_draw_event
    buf, cairo.FORMAT_ARGB32, width, height)
NotImplementedError: Surface.create_for_data: Not Implemented yet.
```

**Comment by hirschmann** [comment]
The error message tells you what is wrong and how to solve it:
```
UserWarning: The Gtk3Agg backend is known to not work on Python 3.x with pycairo. 
Try installing cairocffi.
The Gtk3Agg backend is known to not work on Python 3.x with pycairo.
```

You have 2 options now:
1. do what the error message suggests (install cairocffi), see 
http://stackoverflow.com/questions/33329921/plots-are-not-visible-using-matplotlib-plt-show
2.  select a different matplotlib backend, see 
http://stackoverflow.com/questions/7534453/matplotlib-does-not-show-my-drawings-although-i-call-pyplot-show

**Comment by ghost** [comment]
Hi again,

Had some luck installing alternative Backend
sudo apt-get install libffi-dev
pip install cairocffi

Then worked out that the Backend need to be stated in:
/usr/local/lib/python3.4/dist-packages/matplotlib/mpl-data/matplotlibrc
The line:
backend      :  GTK

Tried several backend names, but not worked as expected. I tried all with "Cairo" but none was able to plot.

In  this setup, could you let me know what value to use?

These are mentioned in the config file
```
# The default backend; one of GTK GTKAgg GTKCairo GTK3Agg GTK3Cairo
# MacOSX Qt4Agg Qt5Agg TkAgg WX WXAgg Agg Cairo GDK PS PDF SVG
# Template.
# You can also deploy your own backend outside of matplotlib by
# referring to the module name (which must be in the PYTHONPATH) as
# 'module://my_backend'.
```

**Comment by ghost** [comment]
I got it working, used:
backend : GTK3Cairo

Now it works :o) thanks a lot for helping out

**Comment by ghost** [comment]
I can run the examples etc:
Python3 sim.py --atune --volume 50 --power 4

Nice

**Comment by ghost** [comment]
Did autotune simulation on my system:
python3 sim.py --atune --volume 20 --power 1.7 -e

I checked from the data that the risetime of the system is like in my setup 1 DEG/min

Impressive

**Comment by hirschmann** [comment]
Thanks for the feedback 👍
